-- MySQL Script generated by MySQL Workbench
-- Wed Oct  5 05:07:03 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sysventas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sysventas` ;

-- -----------------------------------------------------
-- Schema sysventas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sysventas` DEFAULT CHARACTER SET utf8mb4 ;
USE `sysventas` ;

-- -----------------------------------------------------
-- Table `sysventas`.`clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sysventas`.`clientes` ;

CREATE TABLE IF NOT EXISTS `sysventas`.`clientes` (
  `IdCliente` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombres_Apellidos` VARCHAR(50) NOT NULL,
  `Correo_electronico` VARCHAR(50) NOT NULL,
  `Telefono` VARCHAR(50) NOT NULL,
  `Comentarios` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`IdCliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sysventas`.`detalleventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sysventas`.`detalleventas` ;

CREATE TABLE IF NOT EXISTS `sysventas`.`detalleventas` (
  `IdDetalleVenta` INT(11) NOT NULL AUTO_INCREMENT,
  `IdVenta` INT(11) NOT NULL,
  `IdProducto` INT(11) NOT NULL,
  `cantidad` INT(11) NOT NULL,
  `descuento` DECIMAL(18,2) NULL DEFAULT NULL,
  PRIMARY KEY (`IdDetalleVenta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `IdVenta` ON `sysventas`.`detalleventas` (`IdVenta` ASC) VISIBLE;

CREATE INDEX `IdProducto` ON `sysventas`.`detalleventas` (`IdProducto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sysventas`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sysventas`.`productos` ;

CREATE TABLE IF NOT EXISTS `sysventas`.`productos` (
  `IdProducto` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre_producto` VARCHAR(45) NOT NULL,
  `precio` DECIMAL(18,2) NOT NULL,
  PRIMARY KEY (`IdProducto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sysventas`.`ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sysventas`.`ventas` ;

CREATE TABLE IF NOT EXISTS `sysventas`.`ventas` (
  `IdVenta` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha_registro` DATE NULL DEFAULT NULL,
  `IdCliente` INT(11) NOT NULL,
  PRIMARY KEY (`IdVenta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `IdCliente` ON `sysventas`.`ventas` (`IdCliente` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
